# Generated by Django 5.2.6 on 2025-09-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macrastaff',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated list of skills (e.g. Telecommunications, Broadcasting)', max_length=255, null=True),
        ),
    ]
